-- 1. Rules Table
-- Purpose: Stores every NL rule Amara learns
CREATE TABLE IF NOT EXISTS rules (
    id TEXT PRIMARY KEY,
    natural_language TEXT NOT NULL,
    structured_json JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    is_active BOOLEAN DEFAULT true,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Events Table
-- Purpose: Stores file events detected by Amara
CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id TEXT, -- Optional FK to rules(id)
    file_path TEXT NOT NULL,
    details TEXT, -- The column that was missing or named differently
    match_details TEXT, -- Alias if 'details' causes issues, but code uses 'details'
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Telemetry Table
-- Purpose: Stores metrics (events, matches, errors)
CREATE TABLE IF NOT EXISTS telemetry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_count INTEGER DEFAULT 0,
    match_count INTEGER DEFAULT 0,
    error_count INTEGER DEFAULT 0,
    uptime_seconds INTEGER DEFAULT 0,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS on all tables
ALTER TABLE rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE telemetry ENABLE ROW LEVEL SECURITY;

-- Create Policies (For Demo/Development - Open Access)
-- WARNING: In production, restrict these to authenticated users via auth.uid()

-- Rules
CREATE POLICY "Allow public read rules" ON rules FOR SELECT USING (true);
CREATE POLICY "Allow public insert rules" ON rules FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update rules" ON rules FOR UPDATE USING (true);

-- Events
CREATE POLICY "Allow public read events" ON events FOR SELECT USING (true);
CREATE POLICY "Allow public insert events" ON events FOR INSERT WITH CHECK (true);

-- Telemetry
CREATE POLICY "Allow public read telemetry" ON telemetry FOR SELECT USING (true);
CREATE POLICY "Allow public insert telemetry" ON telemetry FOR INSERT WITH CHECK (true);
